version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true
    depends_on:
    - backend
  backend:
    container_name: "backend"
    build: ./backend
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
 mongodb: