swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  
paths:
  /account:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account
      description: API for Account
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountId
          in: query
          description: accountId of account to return array of transactions objects
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Account Successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        400:
          description: Invalid account id
        500:
          description: Internal Server Error
  /account/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account transaction
      description: API for Account transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: query
          description: transactionId of transaction to return
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Transaction Successfully
          schema:
            $ref: '#/definitions/AccountTransactionResponse'
        400:
          description: Invalid Transaction id
        500:
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account transaction update
      description: API for Account transaction update
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Account Transaction Update Payload
          required: true
          schema:
            $ref: '#/definitions/AccountTransactionUpdate'
      produces:
        - application/json
      responses:
        200:
          description: Transaction Successfully
          schema:
            $ref: '#/definitions/AccountTransactionUpdateResponse'
        400:
          description: Invalid Transaction
        500:
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account transaction create
      description: API for Account transaction create
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Account Transaction create Payload
          required: true
          schema:
            $ref: '#/definitions/AccountTransactionCreate'
      produces:
        - application/json
      responses:
        200:
          description: Account Successfully
          schema:
            $ref: '#/definitions/AccountTransactionCreateResponse'
        400:
          description: Invalid Transaction
        500:
          description: Internal Server Error

definitions:
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items :
          type: object
          properties:
              id:
                type: string
              date:
                type: string
                format: date
              description:
                type: string
              amount:
                type: number
                format: float
              balance:
                type: number
                format: float
              transaction:
                type: string
              category:
                type: number
              note:
                type: string
  AccountTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
            format: date
          description:
            type: string
          amount:
            type: number
            format: float
          balance:
            type: number
            format: float
          transaction:
            type: string
          category:
            type: number
          note:
            type: string
  AccountTransactionUpdate:
    properties:
      id:
        type: string
      category:
        type: number
      note:
        type: string
  AccountTransactionUpdateResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  AccountTransactionCreate:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          date:
            type: string
            format: date
          description:
            type: string
          amount:
            type: number
            format: float
          balance:
            type: number
            format: float
          transaction:
            type: string
          category:
            type: number
          note:
            type: string
  AccountTransactionCreateResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
